import type { Customer, ItemCatalogEntry, SalesOrder } from '../types/sales'

export const customers: Customer[] = [
  {
    id: 'cust-1001',
    name: 'Acme Trading Co.',
    address1: '14 Market Street',
    address2: 'Suite 2',
    address3: '',
    suburb: 'Riverside',
    state: 'NSW',
    postCode: '2000',
  },
  {
    id: 'cust-1002',
    name: 'Northern Supplies',
    address1: '81 King Road',
    address2: '',
    address3: '',
    suburb: 'Hillcrest',
    state: 'VIC',
    postCode: '3000',
  },
  {
    id: 'cust-1003',
    name: 'Blue Horizon Retail',
    address1: '55 Ocean Avenue',
    address2: 'Unit 9',
    address3: '',
    suburb: 'Seaside',
    state: 'QLD',
    postCode: '4000',
  },
]

export const catalogItems: ItemCatalogEntry[] = [
  {
    id: 'item-101',
    code: 'ITM-101',
    description: 'Standard Widget',
    price: 45,
    defaultTaxRate: 10,
  },
  {
    id: 'item-102',
    code: 'ITM-102',
    description: 'Premium Widget',
    price: 75,
    defaultTaxRate: 10,
  },
  {
    id: 'item-103',
    code: 'ITM-103',
    description: 'Service Charge',
    price: 120,
    defaultTaxRate: 15,
  },
]

export const mockOrders: SalesOrder[] = [
  {
    id: 'SO-0001',
    customerId: 'cust-1001',
    customerName: 'Acme Trading Co.',
    address1: '14 Market Street',
    address2: 'Suite 2',
    address3: '',
    suburb: 'Riverside',
    state: 'NSW',
    postCode: '2000',
    invoiceNo: 'INV-2301',
    invoiceDate: '2026-04-20',
    referenceNo: 'REF-2026-01',
    note: 'Deliver before end of month.',
    lineItems: [
      {
        id: 'li-01',
        itemId: 'item-101',
        itemCode: 'ITM-101',
        description: 'Standard Widget',
        note: 'Blue packaging',
        quantity: 6,
        price: 45,
        taxRate: 10,
      },
      {
        id: 'li-02',
        itemId: 'item-103',
        itemCode: 'ITM-103',
        description: 'Service Charge',
        note: '',
        quantity: 1,
        price: 120,
        taxRate: 15,
      },
    ],
  },
  {
    id: 'SO-0002',
    customerId: 'cust-1002',
    customerName: 'Northern Supplies',
    address1: '81 King Road',
    address2: '',
    address3: '',
    suburb: 'Hillcrest',
    state: 'VIC',
    postCode: '3000',
    invoiceNo: 'INV-2302',
    invoiceDate: '2026-04-22',
    referenceNo: 'REF-2026-02',
    note: 'Call on arrival.',
    lineItems: [
      {
        id: 'li-03',
        itemId: 'item-102',
        itemCode: 'ITM-102',
        description: 'Premium Widget',
        note: '',
        quantity: 4,
        price: 75,
        taxRate: 10,
      },
    ],
  },
]
